name: NeptuneOD

channels:
  - conda-forge
  - tudat-team
  - tudat-team/label/dev
dependencies:
  - python=3.12
  - pip>=23.3          # Ensure pip supports 
  - setuptools>=69
  - wheel
  - pytest
  - ruff

  # Tudatpy requirements
  - tudatpy=1.0.0.dev53
  - matplotlib # =3.9.2 Maybe this breaks stuff
  - scipy
  - pandas
  - astropy
  - tqdm      
  - astropy-healpix  
  - spiceypy # for automatic data downloader and kernel converter
  - tabulate
  - colorama
  - numpy # <2.0.0 Maybe this breaks some stuff?

  # orbitdet requirements
  - hydra-core
  - beautifulsoup4

  - pip:
    # Tudatpy requirements
    - astroquery>=0.4.8.dev9306
    - git+https://github.com/NASA-PDS/PyTrk234.git
    
    # Install orbitdet program
    - -e .